### ISSUE TITLE
wykop_sdk_reloaded zamiast nbp_sdk w pyproject.toml

### ISSUE THREAD

**Issue by Sygyzmundovych** [lukas346/nbp_sdk#1]
Wielkie dzięki za projekt! Pomógł mi przy rozliczaniu PIT'a :-)

Mała uwaga do
```
[project.urls]
Homepage = "https://github.com/lukas346/wykop_sdk_reloaded"
Issues = "https://github.com/lukas346/wykop_sdk_reloaded/issues"
```
w `pyproject.toml`, gdyż te wartości raczej powinny wskazywać na bieżące repozytorium.

Pozdrawiam.

**Comment by lukas346** [comment]
Dzięki, poprawione 👍
